name: deploy ansible

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: "ansible/*"

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v1
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: docs.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: ourhost ansible_host=163.172.134.70 ansible_user=root
          requirements: requirements.yml
          vault_password: ${{secrets.VAULT_PASSWORD}}
